import http, { FractalResponseData } from '@/api/http';

export interface ServerSubdomain {
    id: number;
    subdomain: string;
    domain: string;
    fqdn: string;
    ipAddress: string;
    isAutoGenerated: boolean;
}

export const rawDataToServerSubdomain = ({ attributes: data }: FractalResponseData): ServerSubdomain => ({
    id: data.id,
    subdomain: data.subdomain,
    domain: data.domain,
    fqdn: data.fqdn,
    ipAddress: data.ip_address,
    isAutoGenerated: data.is_auto_generated,
});

export default async (uuid: string): Promise<ServerSubdomain[]> => {
    const { data } = await http.get(`/api/client/servers/${uuid}/subdomain`);

    return (data.data || []).map((item: any) => rawDataToServerSubdomain(item));
};
