import http, { FractalResponseData } from '@/api/http';

export interface ServerSubdomain {
    id: number;
    subdomain: string;
    domain: string;
    fqdn: string;
    ipAddress: string;
    isAutoGenerated: boolean;
}

export interface SubdomainResponse {
    subdomains: ServerSubdomain[];
    meta: {
        maxPerServer: number;
        customCount: number;
    };
}

export const rawDataToServerSubdomain = ({ attributes: data }: FractalResponseData): ServerSubdomain => ({
    id: data.id,
    subdomain: data.subdomain,
    domain: data.domain,
    fqdn: data.fqdn,
    ipAddress: data.ip_address,
    isAutoGenerated: data.is_auto_generated,
});

export default async (uuid: string): Promise<SubdomainResponse> => {
    const { data } = await http.get(`/api/client/servers/${uuid}/subdomain`);

    return {
        subdomains: (data.data || []).map(rawDataToServerSubdomain),
        meta: {
            maxPerServer: data.meta?.max_per_server ?? 1,
            customCount: data.meta?.custom_count ?? 0,
        },
    };
};
